### ISSUE TITLE
Package compatibility?

### ISSUE THREAD

**Issue by jaimiles23** [pzivich/zEpid#155]
Hi - I'm a big fan of all the work you've done & I'm excited to start using the zEpid package! 

One quick note about package compatibility; when I pip install zepid 0.8.2, I get the following compatibility requirement error:
```
zepid 0.8.2 has requirement matplotlib<3.1,>=2.0, but you'll have matplotlib 3.3.3 which is incompatible.
```

In your package [requirements](https://github.com/pzivich/zEpid/blob/master/travis-requirements.txt), you specify `matplotlib>=2.1.0`. I believe that a different package dependency requires matplotlib<3.1. I can re-run the pip install and it will install a compatible version of matplotlib (3.0.3). 
 

I'm still troubleshooting, but I thought I'd bring this to your attention. Thanks!

**Comment by pzivich** [comment]
Hi @jaimiles23 glad to hear you are looking forward to using the package! 

Thank you for reminder me about this. I will update the version requirements in the 0.9.0 release #143 The matplotlib requirement was because there was a dependency around the release of 3.1 that didn't agree with one of the other other core packages (it was either scipy or numpy). This caused issues with the TravisCI check. The requirements file tells TravisCI to install a specific version of the package for the tests. To avoid that issue for users around release, I added the compatibility. On my computer, I have ran all the tests with matplotlib 3.3.1 (3.3.3 is the latest release) this week. So those issues have been resolved (and I can update the requirements)

If you want to use the newer version of matplotlib, I believe you can get around this by first installing zEpid with a compatible matplotlib version, then upgrading matplotlib via pip. This makes it so that zEpid is installed, but it doesn't check the dependencies. At least I am pretty sure this approach works. After you upgrade matplotlib, you can always check all the plotting functions by copying the script [HERE](https://github.com/pzivich/zEpid/blob/master/tests/graphics_manualtest.py), and running it (you will need to uncomment out the last 4 lines). My plan is to release 0.9.0 soon (like before 2021), so if you want to wait till release and upgrade both zEpid and matplotlib that is also an option.

Also there are some starting tutorials at the [ReadTheDocs site](https://zepid.readthedocs.io/en/latest/index.html), which are more over overviews of the library. The Python tutorials go more indepth into (most) of the functions. If you have any questions, feel free to open an Issue or start a Discussion in the Discussion tab

**Comment by jaimiles23** [comment]
Hi @pzivich!

Thank you for the thorough reply! I appreciate the explanation on how to circumvent the package dependencies – this explains why I was able to get zepid working through repeat installs. I’m glad that this was already on your radar and I look forward to the upcoming 0.9.0 release!

I’ve started to work through your [Python-for-Epidemiologists](https://github.com/pzivich/Python-for-Epidemiologists) repo & plan to tackle the ReadTheDocs tutorials next. I’ll keep you in the loop incase anything else catches my eye.

Thank you for all of your work putting this together & stay safe!
