### ISSUE TITLE
Superlearn check weights

### ISSUE THREAD

**Issue by miaow27** [pzivich/zEpid#168]
@pzivich , Is there anyway to know the final weights for superleaner candidate? 
In R package `tmle`, you can simply call `tmle$Qinit$coef` or `tmle$g$coef` to know the actual weights for Q and g model. 

Thanks!

**Comment by pzivich** [comment]
Yes, calling `SuperLearner.summary()` returns the weights given to each learner.

If this is related to #167 then things aren't as straightforward. `summary()` is not called because of the volume of output. The cross-fit procedure means that there are multiple SL fit to each partition of the data (a min of 2 for single cross-fit). A number of different partitions are done by the cross-fitting procedure. As the recommendation is like 100 different partitions, the weights for each partition are not output (printed or saved). 

I will consider how that could be added to things like `SingleCrossfitTMLE`

**Comment by miaow27** [comment]
Thank you @pzivich! able to know weights (at least average weights across each partition) for the model candidates would be very helpful! 

Also, I am comparing using R's TMLE result and `zEpid`. I thought the result is quite interesting.
-  for parametric TMLE, both estimates and CI, P-value are very very close. 
-  for utilizing Machine Learning, 
  -  without using Singlecorssfit, the CI/P-value from `zEpid` is way too narrow
  -  However, by using Singlecrossfit (default setting), the CI/P-value is much similar (`zEpid` could be more conservative sometimes but conclusion are same as of using R)
  - It is quite interesting that even though the inference method between R and `SingleCrossFit` is different, it yields similar results
