### ISSUE TITLE
Unable to install latest 0.9.0 version through pip

### ISSUE THREAD

**Issue by aidanberry12** [pzivich/zEpid#170]
Using the latest version of `pip 22.2.2` I am unable to install the most recent zEpid 0.9.0 release on python 3.7.0

`pip install -Iv zepid==0.9.0`

`ERROR: Could not find a version that satisfies the requirement zepid==0.9.0 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.5, 0.1.6, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.5.1, 0.5.2, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.8.2)
ERROR: No matching distribution found for zepid==0.9.0`

**Comment by pzivich** [comment]
What happens if you run `pip install zepid`? 0.9.0 is the latest available version, so pip should install that version by default.

It's been awhile since I've had to do much with pip, what's the `-Iv` flag for? If you have a previous install of zepid in your 3.7.0, you might need to uninstall first before you can use the version specific flag (I think)

**Comment by pzivich** [comment]
So zepid==0.9.0 should be available to 3.7.0 (version of a package not available for a Python verion is how I've had that error comes up before in other contexts). I can try testing on one of my machines (I probably can't get to this week since I need to get 3.7.0 with that version of pip together). What OS is this happening on?

While I try to figure out the source of the issue, a simple solution to get 0.9.0 on your machine is to locally install. The way to do that is 
- Clone the GitHub repo to your machine. 
- Open command prompt (windows) or terminal (mac/linux)
- Navigate to the folder, like `cd file/path/to/zEpid`
- Run `python -m pip install .` 

That last command should have pip call the setup.py file in the `zEpid` folder and install zepid manually. To make sure the correct version was installed, you can run
```
import zepid
print(zepid.__version__)
```
which should print 0.9.0 if everything was successful

I would also uninstall the current version of zepid on your machine before doing the local install approach (I don't think it will cause any issues but just to avoid any potential version conflicts).

**Comment by aidanberry12** [comment]
The manual install outlined above works, but I would like to be able to install through pip normally for reproducibility and dependency management. The OS for this error is Red Hat Enterprise License (RHEL) 7.9. Thanks!

**Comment by pzivich** [comment]
absolutely, I just wanted to give you a quick fix while I try to figure out what's going wrong with the pip install

**Comment by pzivich** [comment]
Hi @aidanberry12 I put out v0.9.1, which only had some very minor changes. Can you see if that version is available for you?

I was able to successfully install v0.9.1 on Python 3.7.0 on a few different OS (but not RHEL as I don't have any machines running that currently)

**Comment by aidanberry12** [comment]
Hi Paul. I have verified the latest 0.9.1 version installs on linux and windows, but the RHEL install still doesn't work and it can only find up to 0.8..2. This could definitely be an issue with our enterprise firewall since the successful installs were on my personal computer. Thanks for checking back in on this!
